benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 512, multiplier: 2}, dtype: "float32",  mesh_shape: "8x16", ici_size_range: 128, op_dimension: "4x4x1"}
  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_gather_3d"
  csv_path: "../microbenchmarks/all_gather_3d"
  xlml_metrics_dir: "../microbenchmarks/all_gather_3d"
  xla_dump_dir: "../microbenchmarks/all_gather_3d/hlo_graphs"