benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 128, end: 16384, increase_by: 2048}, dtype: "float32",  mesh_shape: "8x4x4", ici_size_range: 128, op_dimension: "1x1x4"}
  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_gather_1d"
  csv_path: "../microbenchmarks/all_gather_1d"
  xlml_metrics_dir: "../microbenchmarks/all_gather_1d"
  xla_dump_dir: "../microbenchmarks/all_gather_1d/hlo_graphs"