benchmarks:
- benchmark_name: "gemm"
  trace_dir: "../microbenchmarks/gemm"
  csv_path: "../microbenchmarks/gemm"
  xlml_metrics_dir: "../microbenchmarks/gemm"
  xla_dump_dir: "../microbenchmarks/gemm/hlo_graphs"
  num_runs: 100
  benchmark_sweep_params:
  - {m: 4096, k: 4096, n: 4096 }
  - {m: 4096, k: 4096, n: 4096, dtype: 'bfloat16'}