benchmarks:
- benchmark_name: "gemm_multiple_run"
  trace_dir: "../microbenchmarks/gemm_multiple_run_bf16"
  csv_path: "../microbenchmarks/gemm_multiple_run_bf16"
  xlml_metrics_dir: "../microbenchmarks/gemm_multiple_run_bf16"
  xla_dump_dir: "../microbenchmarks/gemm_multiple_run_bf16/hlo_graphs"
  benchmark_sweep_params:
  - {m: 1, k: 4096, n: 4096, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 8192, n: 8192, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 8192, n: 1024, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 1024, n: 8192, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 576, n: 7168, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 7168, n: 2112, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 1536, n: 24576, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 512, n: 32768, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 16384, n: 7168, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 7168, n: 4096, num_runs: 100, dtype: 'bfloat16'}
  - {m: 1, k: 2048, n: 7168, num_runs: 100, dtype: 'bfloat16'}

- benchmark_name: "gemm_multiple_run"
  trace_dir: "../microbenchmarks/gemm_multiple_run_fp8"
  csv_path: "../microbenchmarks/gemm_multiple_run_fp8"
  xlml_metrics_dir: "../microbenchmarks/gemm_multiple_run_fp8"
  xla_dump_dir: "../microbenchmarks/gemm_multiple_run_fp8/hlo_graphs"
  benchmark_sweep_params:
  - {m: 1, k: 4096, n: 4096, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 8192, n: 8192, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 8192, n: 1024, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 1024, n: 8192, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 576, n: 7168, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 7168, n: 2112, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 1536, n: 24576, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 512, n: 32768, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 16384, n: 7168, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 7168, n: 4096, num_runs: 100, dtype: 'float8'}
  - {m: 1, k: 2048, n: 7168, num_runs: 100, dtype: 'float8'}
