benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 512, end: 512, multiplier: 2}, dtype: "float32",  mesh_shape: "4x32", ici_size_range: 128, op_dimension: "1x32"} # Non Parallel Replica
  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_to_all_2d"
  csv_path: "../microbenchmarks/all_to_all_2d"
  xlml_metrics_dir: "../microbenchmarks/all_to_all_2d"
  xla_dump_dir: "../microbenchmarks/all_to_all_2d/hlo_graphs"