benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 512, multiplier: 2}, dtype: "float32",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "1x4x1", op_dimension: 1}
  - {matrix_dim_range: {start: 2, end: 512, multiplier: 2}, dtype: "float32",  mesh_shape: "4x16x2", ici_size_range: 128, sharding_strategy: "1x16x1", op_dimension: 2}
  - {matrix_dim_range: {start: 2, end: 512, multiplier: 2}, dtype: "float32",  mesh_shape: "64x2", ici_size_range: 128, sharding_strategy: "64x1", op_dimension: 3}

  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_gather_demo"
  csv_path: "../microbenchmarks/all_gather_demo"
  xlml_metrics_dir: "../microbenchmarks/all_gather_demo"
  xla_dump_dir: "../microbenchmarks/all_gather_demo/hlo_graphs"