benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 16, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4x2", ici_size_range: 32, sharding_strategy: "4x4x1", op_dimension: 1, num_runs: 20} # Parallel Replica
  - {matrix_dim_range: {start: 16, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4x2", ici_size_range: 32, sharding_strategy: "4x4x2", op_dimension: 1,  num_runs: 20} # Non-Parallel Replica
  trace_dir: "../microbenchmarks/all_gather_tpu7x_2x2x4"
  csv_path: "../microbenchmarks/all_gather_tpu7x_2x2x4"
  xlml_metrics_dir: "../microbenchmarks/all_gather_tpu7x_2x2x4"
  xla_dump_dir: "../microbenchmarks/all_gather_tpu7x_2x2x4/hlo_graphs"