benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 128, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "32x4x2", ici_size_range: 256, sharding_strategy: "32x4x1", op_dimension: 1, num_runs: 5} # Parallel Replica
  - {matrix_dim_range: {start: 128, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "32x4x2", ici_size_range: 256, sharding_strategy: "32x4x2", op_dimension: 1,  num_runs: 5} # Non-Parallel Replica
  trace_dir: "../microbenchmarks/all_gather_tpu7x_4x4x8"
  csv_path: "../microbenchmarks/all_gather_tpu7x_4x4x8"
  xlml_metrics_dir: "../microbenchmarks/all_gather_tpu7x_4x4x8"
  xla_dump_dir: "../microbenchmarks/all_gather_tpu7x_4x4x8/hlo_graphs"