benchmarks:
- benchmark_name: psum
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 32, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "8x4x2", ici_size_range: 64, sharding_strategy: "8x4x1", op_dimension: 1, num_runs: 5} # Parallel Replica
  - {matrix_dim_range: {start: 32, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "8x4x2", ici_size_range: 64, sharding_strategy: "8x4x2", op_dimension: 1,  num_runs: 5} # Non-Parallel Replica
  trace_dir: "../microbenchmarks/psum_tpu7x_2x4x4"
  csv_path: "../microbenchmarks/psum_tpu7x_2x4x4"
  xlml_metrics_dir: "../microbenchmarks/psum_tpu7x_2x4x4"
  xla_dump_dir: "../microbenchmarks/psum_tpu7x_2x4x4/hlo_graphs"