benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "16x4x1", op_dimension: 1, num_runs: 10}
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 2}, dtype: "float16",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "16x4x1", op_dimension: 1, num_runs: 10}
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 2}, dtype: "float8",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "16x4x1", op_dimension: 1, num_runs: 10}
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 2}, dtype: "float4",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "16x4x1", op_dimension: 1, num_runs: 10}
  - {matrix_dim_range: {start: 64, end: 16384, multiplier: 2}, dtype: "bfloat16",  mesh_shape: "16x4x2", ici_size_range: 128, sharding_strategy: "16x4x1", op_dimension: 1, num_runs: 10}
  trace_dir: "../microbenchmarks/all_gather_tpu7x_4x4x4"
  csv_path: "../microbenchmarks/all_gather_tpu7x_4x4x4"
  xlml_metrics_dir: "../microbenchmarks/all_gather_tpu7x_4x4x4"
  xla_dump_dir: "../microbenchmarks/all_gather_tpu7x_4x4x4/hlo_graphs"
