benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 32768, multiplier: 2}, dtype: "float32",  mesh_shape: "4x4x8", ici_size_range: 128, op_dimension: "4x4x8"} # Non Parallel Replica Groups
  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_to_all_3d"
  csv_path: "../microbenchmarks/all_to_all_3d"
  xlml_metrics_dir: "../microbenchmarks/all_to_all_3d"
  xla_dump_dir: "../microbenchmarks/all_to_all_3d/hlo_graphs"