benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 8, end: 16384, multiplier: 2}, dtype: "float32",  mesh_shape: "4x2x2", ici_size_range: 16, sharding_strategy: "4x2x1", op_dimension: 1, num_runs: 5}
  trace_dir: "../microbenchmarks/all_to_all_tpu7x_2x2x2"
  csv_path: "../microbenchmarks/all_to_all_tpu7x_2x2x2"
  xlml_metrics_dir: "../microbenchmarks/all_to_all_tpu7x_2x2x2"
  xla_dump_dir: "../microbenchmarks/all_to_all_tpu7x_2x2x2/hlo_graphs"