benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 524288, multiplier: 2}, dtype: float32, mesh_shape: 2048x2, ici_size_range: 4096, sharding_strategy: 2048x1, op_dimension: 3, num_runs: 5}
  - {matrix_dim_range: {start: 2, end: 524288, multiplier: 2}, dtype: float32, mesh_shape: 8x16x32, ici_size_range: 4096, sharding_strategy: 8x16x32, op_dimension: 3, num_runs: 5}
  trace_dir: ../microbenchmarks/all_gather_3d
  csv_path: ../microbenchmarks/all_gather_3d
  xlml_metrics_dir: ../microbenchmarks/all_gather_3d
  xla_dump_dir: ../microbenchmarks/all_gather_3d/hlo_graphs
