benchmarks:
- benchmark_name: "gemm_batched_simple"
  trace_dir: "../microbenchmarks/gemm_batched_simple_inference"
  csv_path: "../microbenchmarks/gemm_batched_simple_inference"
  xlml_metrics_dir: "../microbenchmarks/gemm_batched_simple_inference"
  num_runs: 1000
  benchmark_sweep_params:
  - {b: {start: 4, end: 256, multiplier: 2}, m: {start: 512, end: 65536, multiplier: 2}, k: {start: 512, end: 65536, multiplier: 2}, n: {start: 512, end: 65536, multiplier: 2}, in_dtype_str: "bf16", out_dtype_str: "bf16"}
