benchmarks:
- benchmark_name: "single_chip_hbm_copy"
  benchmark_sweep_params:
    #- {num_elements_range: {start: 131072, end: 2147483648, multiplier: 2}, dtype: "bfloat16", num_runs: 100}
  - {num_elements_range: {start: 262144, end: 4294967296, multiplier: 2}, dtype: "float8", num_runs: 100}
  trace_dir: "/tmp/microbenchmarks/hbm"
  csv_path: "/tmp/microbenchmarks/hbm"
  xlml_metrics_dir: "/tmp/microbenchmarks/hbm"

