benchmarks:
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 256, end: 32768, multiplier: 2}, dtype: "bfloat16", dcn_size_range: 1, ici_size_range: 256, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/outputs"
  csv_path: "/tmp/microbenchmarks/outputs"
- benchmark_name: all_to_all
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 256, end: 32768, multiplier: 2}, dtype: "float32", dcn_size_range: 1, ici_size_range: 256, num_runs: 100}
  xlml_metrics_dir: "/tmp/microbenchmarks/outputs"
  trace_dir: "/tmp/microbenchmarks/outputs"
  csv_path: "/tmp/microbenchmarks/outputs"