benchmarks:
- benchmark_name: "gemm_simple"
  trace_dir: "../microbenchmarks/gemm_throttling_small"
  csv_path: "../microbenchmarks/gemm_throttling_small"
  xlml_metrics_dir: "../microbenchmarks/gemm_throttling_small"
  xla_dump_dir: "../microbenchmarks/gemm_throttling_small/hlo_graphs"
  benchmark_sweep_params:
  - {m: 64, k: 64, n: 16384, num_runs: 10000}
