benchmarks:
- benchmark_name: "gemm_throttling"
  trace_dir: "../microbenchmarks/gemm_throttling_large_fp8"
  csv_path: "../microbenchmarks/gemm_throttling_large_fp8"
  xlml_metrics_dir: "../microbenchmarks/gemm_throttling_large_fp8"
  xla_dump_dir: "../microbenchmarks/gemm_throttling_large_fp8/hlo_graphs"
  benchmark_sweep_params:
  - {m: 16384, k: 18432, n: 16384, num_runs: 10000, dtype: 'float8'}
