benchmarks:
- benchmark_name: all_gather
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 16384, end: 32768, increase_by: 8192}, dtype: "bfloat16", dcn_size_range: 1, mesh_shape: "8x4x4", ici_size_range: 128, op_dimension: "1x4x4"}
  - {matrix_dim_range: {start: 16384, end: 32768, increase_by: 8192}, dtype: "bfloat16", dcn_size_range: 1, mesh_shape: "8x4x4", ici_size_range: 128, op_dimension: "4x1x4"}
  - {matrix_dim_range: {start: 16384, end: 32768, increase_by: 8192}, dtype: "bfloat16", dcn_size_range: 1, mesh_shape: "8x4x4", ici_size_range: 128, op_dimension: "4x4x1"}
  warmup_tries: 10
  trace_dir: "../microbenchmarks/all_gather_2d"
  csv_path: "../microbenchmarks/all_gather_2d"
  xlml_metrics_dir: "../microbenchmarks/all_gather_2d"
  xla_dump_dir: "../microbenchmarks/all_gather_2d/hlo_graphs"