benchmarks:
- benchmark_name: psum_scatter
  benchmark_sweep_params:
  - {matrix_dim_range: {start: 2, end: 8192, multiplier: 2}, dtype: "float32",  mesh_shape: "8x8x16", ici_size_range: 1024, sharding_strategy: "1x8x1", op_dimension: 1, num_runs: 5} # Parallel Replica Groups (3D)
  - {matrix_dim_range: {start: 2, end: 8192, multiplier: 2}, dtype: "float32",  mesh_shape: "32x32", ici_size_range: 1024, sharding_strategy: "1x32", op_dimension: 1, num_runs: 5} # Non Parallel Replica Groups (2D Flattened)
  trace_dir: "../microbenchmarks/reduce_scatter_2d"
  csv_path: "../microbenchmarks/reduce_scatter_2d"
  xlml_metrics_dir: "../microbenchmarks/reduce_scatter_2d"
  xla_dump_dir: "../microbenchmarks/reduce_scatter_2d/hlo_graphs"